# config.yaml

# Motor driver pins
motor:
  left_pins: [17, 27]
  right_pins: [23, 24]
  pwm_pins: [18, 25]

# Tracker settings
tracker:
  hsv_lower: [90, 50, 50]
  hsv_upper: [130, 255, 255]
  kernel_size: [5, 5]

# Draw settings
draw:
  grid_color: [0, 255, 0]
  text_color: [0, 0, 0]
  fps_color: [0, 0, 0]
  font_scale: 0.7
  thickness: 2
  quadrant_labels:
    - ["Up-Left", "Up", "Up-Right"]
    - ["Left", "Center", "Right"]
    - ["Down-Left", "Down", "Down-Right"]

control:
  proximity_limit_cm:       40.0    # cm at which we consider “blocked”
  sensor_smoothing_alpha:    0.5    # 0 = raw instant, 1 = fully smoothed
  centroid_smoothing_alpha:  0.15   # for fish‐centroid smoothing
  state_debounce_s:          0.3    # min seconds between state changes
  clear_threshold:           3      # AVOID cycles before returning to FOLLOW
  critical_distance_cm:     20.0    # cm for immediate hard‐stop→AVOID

  # new parameters for minimal AVOID duration
  avoid_min_time_s:         2.0     # seconds to stay in AVOID before allowing FOLLOW

  # dynamic sensor‐read interval bounds
  base_sensor_interval_s:   0.20   # “normal” read interval (s)
  min_sensor_interval_s:    0.05   # fastest interval when very close




# Camera settings
camera:
  rotation: 90
  format: "XRGB8888"
  resolution: [640, 480]
  framerate: 30

# Logging level
logging:
  level: "INFO"

# Serial port for Arduino Mega
serial:
  port: "/dev/ttyACM0"
  baudrate: 115200
  timeout_s: 1.0

# Sensor polling
sensor_read:
  num_sensors: 8
  interval_s: 0.2
  labels: ["F","FR","R","BR","B","BL","L","FL"]

# Sensor map
sensor_map:
  - [7, 0, 1]
  - [6, null, 2]
  - [5, 4, 3]

# Braitenberg parameters
braitenberg:
  base_speed: 50.0
  weights_left: [ -0.5, -0.3, 0.0, 0.3, 0.5, 0.3, 0.0, -0.3 ]
  weights_right: [ 0.5, 0.3, 0.0, -0.3, -0.5, -0.3, 0.0, 0.3 ]
